### ISSUE TITLE
Paper link

### ISSUE THREAD

**Issue by macknight** [nidDrBiglr/energy-hackdays-anomaly-detection#4]
Hi,

Any paper link for this repo?

BR

**Comment by nidDrBiglr** [comment]
Hi @macknight,

Thanks for your interest in this project. It was part of a hackathon, meaning there's no paper for it.

You can look at [the pitch](https://github.com/nidDrBiglr/energy-hackdays-anomaly-detection/blob/master/20200829_meterOS_Energy_Data_Hackdays_2020_Pitch.pptx)  we gave for further information though.

Cheers,
David

**Comment by macknight** [comment]
thanks
